name: BForest
version: '${project.version}'
main: my.cufee.bforest.BForest
api-version: '1.20'

commands:
  BFjoin:
    description: Присоедениться к игре.
  BFcreate:
    description: Создать игру (op only)