name: BForest
version: '1.0-SNAPSHOT'
main: my.cufee.bforest.BForest
api-version: '1.20'

commands:
  BFjoin:
    description: Присоедениться к игре.
  BFcreate:
    description: Создать игру (op only).
  BFleave:
    description: Покинуть игру.
  BFdelete:
    description: Удалить игру игру.